# Generated by Django 5.1 on 2024-11-11 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_medida', models.CharField(choices=[('M2', 'M2'), ('UN', 'UN'), ('ROLLO', 'ROLLO'), ('TARRO', 'TARRO'), ('LITRO', 'LITRO')], default='UN', max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'unique_together': {('unidad_medida', 'descripcion')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad_disponible', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unidadmedida')),
            ],
        ),
    ]
