# Generated by Django 5.1 on 2024-11-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadmedida',
            name='unidad_medida',
            field=models.CharField(choices=[('M2', 'M2'), ('UN', 'UN'), ('ROLLO', 'ROLLO'), ('TARRO', 'TARRO'), ('LITRO', 'LITRO')], default='', max_length=10),
        ),
    ]
