# Generated by Django 5.1 on 2024-11-11 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_material_unidad_medida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='stock',
            new_name='stock',
        ),
    ]
