# Generated by Django 5.1 on 2024-11-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedida',
            name='unidad_medida',
            field=models.CharField(choices=[('M2', 'M2'), ('UN', 'UN'), ('ROLLO', 'ROLLO'), ('TARRO', 'TARRO'), ('LITRO', 'LITRO')], default='UN', max_length=10),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='unidadmedida',
            unique_together={('unidad_medida', 'descripcion')},
        ),
    ]
