# Generated by Django 5.1 on 2024-10-02 00:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='cantidad_solicitada',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='codigo_ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='fecha_solicitud',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='material',
        ),
        migrations.AddField(
            model_name='ticket',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='material_solicitado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
