# Generated by Django 5.1 on 2024-10-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0002_remove_customuser_roles_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(related_name='users', to='Polls.role'),
        ),
    ]
