# Generated by Django 5.1 on 2024-11-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0002_alter_unidadmedida_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cobrado', 'Cobrado')], default='pendiente', max_length=20),
        ),
    ]
