# Generated by Django 5.1 on 2024-11-16 01:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0004_alter_customuser_email_alter_customuser_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
