# Generated by Django 5.1 on 2024-10-29 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0004_alter_customuser_roles_alter_role_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='unidad_medida',
            new_name='UnidadMedida',
        ),
    ]
