# Generated by Django 5.1 on 2024-11-16 01:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0005_alter_ticket_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
