# Generated by Django 5.1 on 2024-10-29 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0006_rename_estado_ticket_estadoticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='EstadoTicket',
            new_name='estado_ticket',
        ),
        migrations.RemoveField(
            model_name='material',
            name='UnidadMedida',
        ),
        migrations.AddField(
            model_name='material',
            name='unidad_medida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Polls.unidadmedida'),
        ),
    ]
