# Generated by Django 5.1 on 2024-10-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0007_rename_estadoticket_ticket_estado_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='cantidad_disponible',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='stock_minimo',
            field=models.IntegerField(),
        ),
    ]
