# Generated by Django 5.1 on 2024-11-05 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0008_alter_material_cantidad_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
