# Generated by Django 5.1 on 2024-11-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0009_alter_ticket_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(related_name='users', to='Polls.role'),
        ),
    ]
