# Generated by Django 5.1 on 2024-11-11 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0014_question_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='estado_ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cobrado', 'Cobrado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='material_solicitado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Polls.material'),
            preserve_default=False,
        ),
    ]
