name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia 'main' por tu rama principal si es diferente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Si necesitas generar documentación estática, agrega aquí los comandos (por ejemplo, Sphinx, MkDocs, etc.)
      # - name: Build docs
      #   run: |
      #     cd docs
      #     make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # Cambia esto a la carpeta que contiene tus archivos estáticos
